### ISSUE TITLE
Looking for web developers to create a Vue.js application

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#1]
We'd like to create a webapp for our domotic framework.

The aim is to reproduce all features integrated int our Java frontend https://github.com/freedomotic/freedomotic/tree/master/plugins/devices/frontend-java
To have an idea you can look at our YouTube channel https://www.youtube.com/freedomotic

Time ago we developed a first prototype in Polymer.You can try it by downloading Freedomotic and pointing your browser to http://localhost:8090. A brief video is available on https://www.youtube.com/watch?v=0pN-8mbNuQk
And the source code is hosted on https://github.com/freedomotic/fd-polymer-webapp

Maybe some components can be reused in Vue.js.

The interaction with our framework is based on a RESTful API https://github.com/freedomotic/freedomotic/tree/master/plugins/devices/restapi-v3/src/main/java/com/freedomotic/plugins/devices/restapiv3

Demo available at try http://104.236.92.231:8090/ (credentials admin/admin)
We are defining the webapp structure and the tasks to execute.
If you want to contribute please comment.

**Comment by P3trur0** [comment]
@mcicolella what about to create a first issue about a general scaffolding for this project? I'd expect to have is using webpack to bundle all the stuff together.

**Comment by mcicolella** [comment]
Agree. Can you open it?

**Comment by P3trur0** [comment]
:+1:

**Comment by williamparry** [comment]
Are you looking to preserve the UI look & feel?

**Comment by mcicolella** [comment]
Yes if possible

**Comment by williamparry** [comment]
I've put vue-material into this: https://github.com/freedomotic/fd-vue-webapp/pull/22 is that OK?

**Comment by mcicolella** [comment]
@williamparry I like much!! Thanks
Here a screenshot
![login](https://user-images.githubusercontent.com/4079634/32179673-4d1ea9f4-bd90-11e7-88f7-fd77dc606e40.png)

**Comment by P3trur0** [comment]
Closed with #36
