### ISSUE TITLE
Add vue-axios plugin

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#11]
In order to interact with our Restful API we need to add vue-axios plugin.

**Comment by mcicolella** [comment]
Because I read [here](https://vuejsfeed.com/blog/vue-js-retiring-vue-resource) that Vue.js is retiring vue-resource.

**Comment by bryanjhv** [comment]
Oh. That post just explains that `vuejs/vue-resource` no longer exists because HTTP requests are not a core need for Vue, not that it's bad. Anyway, the methods `vue-axios` exposes are the same. 😄

**Comment by Rud156** [comment]
Why not use just axios?
