### ISSUE TITLE
API to retrieve images from the server doesn't work correctly

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#113]
[Here](https://github.com/freedomotic/fd-vue-webapp/blob/master/src/components/Plugin.vue) an example to retrieve the plugin image.
It uses a [Vuex action](https://github.com/freedomotic/fd-vue-webapp/blob/cecfd8b21b1b190356ebcd6cd5c7f6236cf45935/src/store/actions.js#L193) to perform an Axios request.
The server replies with HTTP 303 status code and the new location but no request is executed.
For example
client request XHR GET http://174.138.4.3:9111/v3/resources/mailer-running.png
server response [HTTP/1.1 303 See Other 94ms] with Location: http://174.138.4.3:9111/v3/resources/mailer-running.png
After that a list of Network errors as

![schermata del 2018-07-07 18-45-47](https://user-images.githubusercontent.com/4079634/42412921-003a6e0c-8216-11e8-9a4b-f54e4671630b.png)

**Comment by mcicolella** [comment]
[This](https://github.com/freedomotic/fd-vue-webapp/blob/956786cb66d9595f03b61021df7460fffd9b4afd/src/store/actions.js#L194) is the updated Vuex action.  
No problem with Chrome. 
Firefox raises a CORS exception
![error_firefox](https://user-images.githubusercontent.com/4079634/42886317-8b5dff40-8aa3-11e8-91cb-244711eaf42a.png)

**Comment by mcicolella** [comment]
@P3trur0 if you have time could you give a try on Firefox?

**Comment by P3trur0** [comment]
@mcicolella ok then, maybe tomorrow I have few spare time. I'll give it a look

**Comment by amenak77** [comment]
Let me know: does #113 is fixed with chrome but not with firefox?

**Comment by amenak77** [comment]
![restapi_err_firefox](https://user-images.githubusercontent.com/13914556/43941202-92ec2df4-9c73-11e8-9461-e74185afdcac.jpg)

cURL Restapi http request with firefox
