### ISSUE TITLE
Retrieve environment background image from API

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#138]
Now the background image is set statically.
It should be retrieved via API (passing "environment.backgroundImage" property to [getResource](https://github.com/freedomotic/fd-vue-webapp/blob/00ed18d5573acab8b4ef54c51843ce6c557f996b/src/components/Environment.vue#L128) method) 
**This requires to fix #113**

**Comment by jtommy** [comment]
@mcicolella There is no 'environment.backgroundImag.png' resource id but it works with 'map2.png'.
Is it correct anyway ?

**Comment by amenak77** [comment]
@jtommy if this may help you: when I want to change freedomotic's background, I rename and replace the new background file as "map2.png". I think it is correct

**Comment by mcicolella** [comment]
Fixed in 19608d391e56dd8b7f2d9a7c1d7bb55501daf7ab
