### ISSUE TITLE
Environment canvas not centered correctly

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#139]
00ed18d5573acab8b4ef54c51843ce6c557f996b introduced scaling for environments. The canvas dimensions are now set to the environment width and height and no more set to static values.
So it's important to scale in order to consider the screen resolution.
There are a couple of issues to fix:
- the canvas is not vertically centered
- it should expand the entire page

Current layout (there are some placeholders for the things images)
![environment-carousel](https://user-images.githubusercontent.com/4079634/43533069-32049e9c-95b4-11e8-875f-eb2832b08a78.png)

Good layout
![polymer-client](https://user-images.githubusercontent.com/4079634/43533119-56b8879e-95b4-11e8-9b67-fc5169f5d7b4.png)

**Comment by amenak77** [comment]
Here is a tip:
HTML
<img src="images/bg.jpg" id="bg" alt="">
CSS
#bg {
  position: fixed; 
  top: 0; 
  left: 0; 
	
  /* Preserve aspet ratio */
  min-width: 100%;
  min-height: 100%;
}

**Comment by bestmazzo** [comment]
#183 Should fix it

**Comment by amenak77** [comment]
Great!

**Comment by mcicolella** [comment]
Thanks @bestmazzo
