### ISSUE TITLE
client webapp menu "things" (lights) doesn't work with Edge

### ISSUE THREAD

**Issue by amenak77** [freedomotic/fd-vue-webapp#146]
If you try to switch on/off a light from menu Things with Edge, it doesn't work (no such a problem with Chrome and FireFox)

**Comment by mcicolella** [comment]
Mobile or desktop version?

**Comment by mcicolella** [comment]
Please check any console error with Dev Tools (F12)

**Comment by amenak77** [comment]
Mobile doesn't work (chrome); I'll check later on edge, and will use dev tools

**Comment by amenak77** [comment]
Downloaded firefox app for android; server address = IP address, server port = 9111; user id = admin, password = admin --> BAD LOGIN

**Comment by amenak77** [comment]
excuse me all,
I've recreated the client test with Edge, and this time it works (and brightness bar moves a little when you switch light on

**Comment by mcicolella** [comment]
Can we close this?

**Comment by amenak77** [comment]
You read my mind. Don't know what happened; maybe this is due to edge's multiple nature. Never happened since then. One detail only: at the time, every light card was darkgrey with dropdown menu opened. We can close it
