### ISSUE TITLE
Show thing details on mouse over its icon

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#148]
We'd show thing details when the mouse is over its icon.

**Comment by amenak77** [comment]
![v-tooltip](https://user-images.githubusercontent.com/13914556/43684179-aa10609e-989b-11e8-9de1-4d5e3e9b1f39.png)

https://github.com/Akryum/v-tooltip   Take a look here

**Comment by mcicolella** [comment]
It seems a good solution.

**Comment by mcicolella** [comment]
Fixed in b2ef9fc201658f2d453117b47ab851b4caa93c3f
