### ISSUE TITLE
webapp client things menu brightness slidebar behavior is variable

### ISSUE THREAD

**Issue by amenak77** [freedomotic/fd-vue-webapp#149]
If you click on client on/off light button placed on menu things of a not dimmer light, brightness slidebar associated with it, shows strange behavior; in most cases doesn't align to on/off, sometimes does it, and sometimes only a little part of the bar moves when light is on. These oddities take place on every kind of browser

**Comment by amenak77** [comment]
![brightness_colo_iss](https://user-images.githubusercontent.com/13914556/43684072-81079688-9899-11e8-9c47-d02a13309306.jpg)

this is what happens when I try to swtch a light on (number 12) with webapp and Chrome; as you can see, this time brightness bar is "lazy" and doesn't move; in console it seems to be present an header error (the "access-control-allow-origin" header is http://localhost:8080 and not http://localhost:8090). Another static variable problem?

**Comment by mcicolella** [comment]
I can't reproduce this issue.

**Comment by amenak77** [comment]
Did you have complie the webapp project and modify the webserver plugin? Because if you haven't done so, you can't have address conflict. Please excuse me for the odd consideration: only the compiled ver is served at 8090

**Comment by amenak77** [comment]
Don't you have any problem with brightness slidebar?

**Comment by mcicolella** [comment]
Of course I have compiled the project but I don't have your address conflict.
Otherwise the slidebar doesn't work well with Firefox. Chrome is OK.

**Comment by amenak77** [comment]
Maybe we haven't centered the relationship between cause and effect about the problem yet. This could explain its non constant nature. Try to run your test again with projec's dev server running underground

**Comment by amenak77** [comment]
![desktop_colo_iss](https://user-images.githubusercontent.com/13914556/43775529-6024fbbc-9a4d-11e8-8ee3-a89ea758ea7f.jpg)

I confirm that, using crome at 8090 with feedomotic webserver plugin, I have header conflict which doesn't show with project served at 8080; in this case the problem is no synoptic shown

**Comment by amenak77** [comment]
So the issue should change in "problems caused by address conflict in client's compled version"

**Comment by mcicolella** [comment]
As I said previously I don't have this problem with Chrome and Webserver plugin

![schermata del 2018-08-07 16-02-01](https://user-images.githubusercontent.com/4079634/43780657-5dada7c2-9a5b-11e8-9ad2-0eeb7a4c5ebc.png)

**Comment by amenak77** [comment]
which Chrome ver do you have?

**Comment by amenak77** [comment]
What if I'd modify manifest file address of webserver plugin to 8080 temporarily? No dev server running, obviously. If the bug vanishes I have an address problem in compiled file

**Comment by mcicolella** [comment]
59.0.3071.109 (Build ufficiale) (a 64 bit)

**Comment by amenak77** [comment]
I have Ver 68.0.3440.84 (Build ufficiale) (a 64 bit); please update your Chrome browser ver and try again

**Comment by amenak77** [comment]
![chrome-client-8080](https://user-images.githubusercontent.com/13914556/43805816-87747ef0-9aa1-11e8-8f36-b7550e9cde8a.jpg)

This is the proof: localhost:8080

**Comment by mcicolella** [comment]
No address conflict with the last Chrome version and compiled version served on port 8090

![schermata del 2018-08-09 12-02-07](https://user-images.githubusercontent.com/4079634/43892496-62f10acc-9bcc-11e8-9a3d-94d8b8032930.png)

![schermata del 2018-08-09 12-02-20](https://user-images.githubusercontent.com/4079634/43892519-741aea3e-9bcc-11e8-9094-cc46ac04a02c.png)

**Comment by amenak77** [comment]
It'strange; is it possible that the problem lays in my repo only? I'll try to update and recomplie. A win problem maybe

**Comment by amenak77** [comment]
![noprob_iss](https://user-images.githubusercontent.com/13914556/43940469-0c144666-9c70-11e8-89b9-bef212ea3b3e.jpg)

project updated and recompiled: issue is no more. Boh! Excuse me for time loss
