### ISSUE TITLE
Create a dashboard for Vuejs client

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#16]
This dashboard can be used for desktop and tablet visualization.
Here the version developed in Polymer

![dashboard](https://user-images.githubusercontent.com/4079634/31911820-3413e382-b842-11e7-922b-81466cfdc040.png)

The [components](https://github.com/freedomotic/fd-polymer-webapp/tree/master/app/elements) should be converted or adapted to the new Vue.js client. 
Demo available at try http://104.236.92.231:8090/ (credentials admin/admin)

**Comment by ninja542** [comment]
so you want to convert polymer components into vue components?

**Comment by amenak77** [comment]
@ninja542 yes! We have a webapp made with Polymer 0.5 and what is already implemented works fine but in the complex the project is a dead end due to major changes needed to convert it to 1.0 ver. first place, and then to 2.0. So we are refactoring web app project with Vue.js. Any help is appreciated, thanks

**Comment by amenak77** [comment]
@ninja542 are you working on this?

**Comment by ninja542** [comment]
ah, I'm just recently learning vue, and I don't know how to work with vue components, so I don't think I can work on this

**Comment by amenak77** [comment]
@ninja542 ok, no problem; maybe is there some other Vue issue about our client, you are interested trying to fix?

**Comment by mcicolella** [comment]
[Here](https://github.com/freedomotic/fd-vue-webapp/blob/master/src/components/Dashboard.vue) a first draft. 
CornerButton components should be set correctly.
Css derives from Polymer element and should be reviewed and adapted.

**Comment by mcicolella** [comment]
A new draft is available. Every corner has its own icon and tooltip.
Material icons used.

![dashboard](https://user-images.githubusercontent.com/4079634/32941565-6cf0bbb0-cb86-11e7-8159-5c5227ead555.png)
