### ISSUE TITLE
Add a background to v-tooltip related to things

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#163]
When you move the mouse over a thing on the floorplan a tooltip shows some related data.
We need to add a background to it (now it's transparent) to make the data more readable.

![schermata del 2018-10-01 17-00-43](https://user-images.githubusercontent.com/4079634/46297050-0e487600-c59c-11e8-9a0f-b0f12a01dd52.png)

Rif. [Environment component](https://github.com/freedomotic/fd-vue-webapp/blob/578072832847faaaa640cbeb40536e305b680469/src/components/Environment.vue#L19)

**Comment by P3trur0** [comment]
@mcicolella I can work on this.

**Comment by P3trur0** [comment]
ok then,
