### ISSUE TITLE
Align tooltip text to left

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#176]
We need to align all tooltip text to left. Now some rows have some blank spaces at beginning.

![schermata del 2018-10-03 10-16-21](https://user-images.githubusercontent.com/4079634/46398545-b02fa600-c6f5-11e8-9df5-33806ff1d001.png)

Rif. [Environment component](https://github.com/freedomotic/fd-vue-webapp/blob/2e4b80cd981d4c52fd656f80e5a5158aae8df6e3/src/components/Environment.vue#L10)

**Comment by P3trur0** [comment]
The problem should be [here](https://github.com/freedomotic/fd-vue-webapp/blob/2e4b80cd981d4c52fd656f80e5a5158aae8df6e3/src/components/Environment.vue#L137).

**Comment by mcicolella** [comment]
Fixed in 8b4c86d38c6120f530631d326353a0fc5e69d383
