### ISSUE TITLE
Refactoring of Environment component layout

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#186]
We need to refactor the layout of [Environment](https://github.com/freedomotic/fd-vue-webapp/blob/master/src/components/Environment.vue) component to include a menu and the environment name.

Starting from the current layout it should be composed by three parts

1. External container including every element
![container](https://user-images.githubusercontent.com/4079634/46619191-cdafa600-cb21-11e8-8c9e-418c632930e5.png)

2. Menu + environment name container
![menu](https://user-images.githubusercontent.com/4079634/46619222-e0c27600-cb21-11e8-8a20-389579603433.png)

3. Environment canvas
![canvas](https://user-images.githubusercontent.com/4079634/46619242-ecae3800-cb21-11e8-8354-2085c8dd7043.png)

It should scale correctly when the windows is resized.

**Comment by mcicolella** [comment]
@DenisG0 would you like to take a look at this?

**Comment by DenisG0** [comment]
Okay, i will give it try

**Comment by mcicolella** [comment]
@DenisG0 great great work! Thanks

**Comment by mcicolella** [comment]
Fixed in b0737000953c18721190edae907b5fd5a218646e
