### ISSUE TITLE
Fix Users panel layout

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#191]
We need to fix 

- the space between the cards
- the icons at top left corner not showed correctly 
- the bottom right button position partially covered by scrollbar

![schermata del 2018-10-12 17-05-48](https://user-images.githubusercontent.com/4079634/46877636-a0c10300-ce41-11e8-9b02-f908d153d4a6.png)

**Comment by Sharma-Hrishabh** [comment]
i can help :)

**Comment by alzaar** [comment]
Hi,
This issue can be easily fixed but when I started working on this I got this.
<img width="1196" alt="screen shot 2019-03-04 at 6 54 08 am" src="https://user-images.githubusercontent.com/39810925/53731963-64229200-3e4a-11e9-8ab2-528bc9618dd6.png">

After following the instructions, when I started the server and used admin for both password and username, I received a message 'bad login information'. Am I doing something wrong here?

**Comment by amenak77** [comment]
Hi Alzaar,
Excuse me for late answer. I've got, since some times now, your same problem. A bad login error manifests itself when I try to run vue webapp project; you can bypass the problem if you compile the app and update the file into Freedomotic webserver plugin; you can see changes poiting from webbrowser to [freedomotic ip address]:8090

**Comment by amenak77** [comment]
Hi Alzaar,
I asked to Mauro about this problem and he confirmed to me that the reason about malfunction is due to a problem with Freedomotic online instance which serves the webapp. We will fix it ASAP. Thanks again for your contribution. Best regards, Alberto

**Comment by amenak77** [comment]
Hi Alzaar,
Freedomotic instance is online again; if you are still interested in fixing panel layout issues, now you can. Have a nice day, Alberto

**Comment by hasan-wajahat** [comment]
hey @mcicolella I created a fix for this but how do I add the fix? I tried pushing my own branch but don't have access to do so. Please let me know what I need to do.

**Comment by mcicolella** [comment]
Fixed with Quasar version.
