### ISSUE TITLE
Connect 'Protocol' field to 'availableProtocols' getter

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#203]
The field [Protocol](https://github.com/freedomotic/fd-vue-webapp/blob/093a7d4f19dd3f109ae0c214e27d7810ed6f8356/src/components/ThingsEditor.vue#L27) should list the available protocols.
These data can be retrieved from Vuex getter [availableProtocols](https://github.com/freedomotic/fd-vue-webapp/blob/093a7d4f19dd3f109ae0c214e27d7810ed6f8356/src/store/getters.js#L5).

![schermata del 2018-10-31 10-28-35](https://user-images.githubusercontent.com/4079634/47778943-44daf300-dcf8-11e8-99c0-776c0f7ca805.png)

**Comment by amenak77** [comment]
![protocol_own](https://user-images.githubusercontent.com/13914556/48282007-bf261880-e458-11e8-9c43-d888e1c258b3.jpg)

I have not this problem

**Comment by amenak77** [comment]
Maybe there is something strange about light's object structure; a question: is it possible having a light object without a protocol?

**Comment by mcicolella** [comment]
Yes, by default protocol and address are set to 'unknown'. In this case you have a virtual object.

**Comment by amenak77** [comment]
Ok, then online demo object light maybe has "unknown" as a protocol by default and vue getter works correcly; in fact it has correctly shown "openwebnet" in 1*41 light of my myhome system; perhaps there is no issue except the idea of virtual object

**Comment by mcicolella** [comment]
If you want to associate/change a protocol you need a list of them as in Jfrontend. This is the issue.
