### ISSUE TITLE
Change of UI Framework

### ISSUE THREAD

**Issue by heywhy** [freedomotic/fd-vue-webapp#207]
I will like to suggest changing the ui framework to [quasar-framework](https://quasar-framework.org) because it is conformant with material design specs and there is the advantage of building for both android and ios from the same codebase. I will suggest you give it a try. As much as I'll love to contribute to this project I don't think its proper having different ui libraries (vue-js-modal, vue-onsenui, e.t.c.) in a single project.

**Comment by amenak77** [comment]
Hi heywhy,
thanks for your contribution to the project; what you suggest is correct, but we have advantages having different ui libraries in the same project; one for all, the possiblity to have different ui automatically (such as desktop and mobile) on different devices served from the same web server plugin; but as your considerations about quasar framework seem interesting, would you be available to create a quasar compatible version of the project? Have a nice evening, Alberto

**Comment by P3trur0** [comment]
@heywhy thank you for your proposal.
Personally I agree with your point of view. I am looking forward to seeing your PR about this enhancement. :muscle: :smiley:

**Comment by amenak77** [comment]
@heywhy thanks again for your most valued contribution; I'm very much curious too to see this incredible project's evolution. Pease let us know about work in progress periodically

**Comment by heywhy** [comment]
you can check this [video](https://www.useloom.com/share/4bfd7e92158c4e3cbd599901eef822aa), though it doesn't contain so much yet.

**Comment by heywhy** [comment]
what do y'all think, of the look?
![screenshot from 2018-12-11 13-29-51](https://user-images.githubusercontent.com/13123868/49800926-0c8ff100-fd49-11e8-9821-2eb17b5072ab.png)

**Comment by heywhy** [comment]
Below is the settings page, someone should be able to help with the flag names (:smile: I don't recognise them) when I make a pull request, I hope to get a feedback soon.
![screenshot from 2018-12-11 16-28-54](https://user-images.githubusercontent.com/13123868/49810676-01958a80-fd62-11e8-9448-8643ba7386b1.png)

**Comment by amenak77** [comment]
@heywhy OK first screenshot to me!! the flags are (from up to down from first vertical row: Norway, Romania, Slovakia, Turkey. Good Job!!!!

**Comment by P3trur0** [comment]
@heywhy  so far it seems brilliant. Are these changes already on your fork?

**Comment by heywhy** [comment]
@P3trur0 The changes are on my fork already.

**Comment by heywhy** [comment]
This is the mobile view also. 
![screenshot from 2018-12-11 19-23-35](https://user-images.githubusercontent.com/13123868/49823532-344e7b80-fd80-11e8-8310-a4324ce56da5.png)
![screenshot from 2018-12-11 20-07-01](https://user-images.githubusercontent.com/13123868/49823593-5d6f0c00-fd80-11e8-8c7d-9f62559667a3.png)

**Comment by amenak77** [comment]
@heywhy fantastic!

**Comment by heywhy** [comment]
I will like y'all to watch this [video](https://www.useloom.com/share/5b66b89d066e45e3bb82bca82144cc52) (I'm sure Y'all will :heart: it).
You should also create a dev branch on this repo so that I can make a pull request towards the dev branch :smile:

**Comment by amenak77** [comment]
@heywhy I love your video  @P3trur0 could you fix the dev branch problem?

**Comment by P3trur0** [comment]
@heywhy currently we have not deployed this application in production so you could safely open your PR on `master`.

**Comment by heywhy** [comment]
@P3trur0 I can't find the development branch on this repo. Are you sure it has been created? :confused:

**Comment by P3trur0** [comment]
@heywhy please, check again.

**Comment by heywhy** [comment]
I had to fork the repo again because of my misunderstanding of the rebase concept :disappointed: , so I screwed somethings but I now understand it. A new pull request has been made.

Actually, today is my first time using `git rebase` which led to screwing up my fork. I now have a better understanding of the concept and how to go about it. :disappointed_relieved:

**Comment by P3trur0** [comment]
@heywhy no problem at all, happy learning! 😄 I'll review it again ASAP.

However, as previously stated, this update to Quasar could be merged only when all the scaffolding will be cleaned up properly. I mean, for example, the content of `a/` directory should be reorganized in the proper directory structure and the application behavior shall be the same as before.
  
So, please, take your time to clean it up accordingly to the project needs and do not hesitate to ping us back in case of doubts and ideas 💪 💡

**Comment by heywhy** [comment]
Okay, I will do that

**Comment by mcicolella** [comment]
Hi @heywhy are you still on this?

**Comment by heywhy** [comment]
@mcicolella I'm sorry for replying now I guess I missed the notification. I'm still on it but I halted the development because of quasar v1 is under development (it's in beta now), I wanted it to be stable enough or officially said it is stable, so that I can continue.

**Comment by heywhy** [comment]
@mcicolella I'm very glad to say I will be continuing the upgrade starting from tommorow, and I hope to complete it before the end of the year. Cheers.

**Comment by amenak77** [comment]
Hi heywhy,
Thank you very much for your contribution; please let us update about your progresses

**Comment by amenak77** [comment]
Hi heywhy,
Any news about your work in progress?

**Comment by mcicolella** [comment]
Closed by 9032e55319cfae9ad2431b29c78a868f223b1f9f
