### ISSUE TITLE
Travis CI fails

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#214]
Travis CI fails with the following error

` { message: 'session not created: Chrome version must be between 71 and 75\n  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-101-generic x86_64) (WARNING: The server did not provide any stacktrace information)\nCommand duration or timeout: 1.05 seconds\nBuild info: version: \'3.141.59\', revision: \'e82be7d358\', time: \'2018-11-14T08:25:53\'\nSystem info: host: \'localhost\', ip: \'127.0.0.1\', os.name: \'Linux\', os.arch: \'amd64\', os.version: \'4.4.0-101-generic\', java.version: \'1.8.0_151\'\nDriver info: driver.version: unknown',
     error: 'session not created' }`

**Comment by amenak77** [comment]
Is it because, chrome is not updated?

**Comment by pat-lego** [comment]
Most likely because of the driver used to connect to chrome is not up to date. TravisCI pulls the latest Chrome browser this is something that is not configurable in TravisCI. 

Check the driver that is being to communicate with TravisCI for updates.

**Comment by amenak77** [comment]
Sort of..... :)

**Comment by amenak77** [comment]
Solution

Keep JDK upgraded to recent levels JDK 8u201.
Uninstall all the instances of Chrome Browser (you can opt to use Revo Uninstaller).
Upgrade ChromeDriver to current ChromeDriver v2.46 level.
Keep Chrome version between Chrome v71-73 levels. (as per ChromeDriver v2.46 release notes)

**Comment by amenak77** [comment]
It is best stackoverflow advice about this  issue 😅
