### ISSUE TITLE
Project build fails

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#217]
When you execute `npm run build` the process fails with the following error

`ERROR in static/js/vendor.8fa79e6c6b85a1d6a429.js from UglifyJs
Unexpected token: name (code) [./~/vue-snotify/vue-snotify.esm.js:104,0][static/js/vendor.8fa79e6c6b85a1d6a429.js:17691,12]

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fd-vue-webapp@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fd-vue-webapp@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by amenak77** [comment]
Ciao a tutti,
Potrebbe esserci una soluzione qui: https://github.com/artemsky/vue-snotify/issues/52 
Sembra un problema legato al fatto che non c’è del codice Vue in sintassi ES6 nel progetto, ma del codice in sintassi ES6 nella versione compilata del modulo. Ci vuole una piccola modifica al codice sorgente. C’è anche un consiglio su come evitare che si crei questo disallineamento. Ciao, Alberto

**Comment by amenak77** [comment]
Hi everyone,
excuse me for my lack in education, but I overreactednand responded in Italian. The issue is probably due to a Vue issue reported nere: artemsky/vue-snotify#52  There is a little code changing to do. Bye, Alberto

**Comment by amenak77** [comment]
Thanks to wmcmurray for reporting

**Comment by mcicolella** [comment]
Thanks @amenak77
