### ISSUE TITLE
Show ThingsEditor dialog when right-click on environment thing

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#219]
When you right-click on a thing inside the environment it should open a Quasar modal with a ThingsEditor component.

Component to change: [Environment](https://github.com/freedomotic/fd-vue-webapp/blob/master/src/components/Environment.vue)
Function to change: [openThingEditor](https://github.com/freedomotic/fd-vue-webapp/blob/bf3bf4e828057f798cf87847ac526104dd40be1e/src/components/Environment.vue#L233)
Behavior to reproduce: [Quasar modal in Thing component](https://github.com/freedomotic/fd-vue-webapp/blob/bf3bf4e828057f798cf87847ac526104dd40be1e/src/components/Thing.vue#L206)

**Comment by P3trur0** [comment]
Hi @mcicolella I can take this 😃
