### ISSUE TITLE
Add background image to Login component

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#224]
Add the background image to Login component as in Dashboard component.

Component to modify:
[Login.vue](https://github.com/freedomotic/fd-vue-webapp/blob/master/src/components/Login.vue) (desktop section / no mobile)

Image to add as background
[bkgnd.jpg](https://github.com/freedomotic/fd-vue-webapp/blob/master/src/assets/bkgnd.jpg)

**Comment by ayushpandey8439** [comment]
Hey, I could work on this if its okay.. :)

**Comment by mcicolella** [comment]
Fixed in #226
