### ISSUE TITLE
Find nice icons for ThingsEditor menu

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#225]
We need nice icons for the menu according with the items (properties, appearance etc)

![Schermata da 2020-10-09 20-43-58](https://user-images.githubusercontent.com/4079634/95620494-90fc4980-0a70-11eb-958a-4ea2c2cb079b.png)

Component to modify
[ThingsEditor](https://github.com/freedomotic/fd-vue-webapp/blob/master/src/components/ThingsEditor.vue)

**Comment by leobia** [comment]
Hi! I would like to help you on this issue. I'll send a pull request with a screenshot of the new Icons.

**Comment by mcicolella** [comment]
Fixed in #229
