### ISSUE TITLE
Disable expand arrow in Thing card when the beaviours list is empty

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#228]
Some things have an empty behaviours list.
In this case we should disable the expand arrow.

![Schermata da 2020-10-10 08-48-41](https://user-images.githubusercontent.com/4079634/95648163-6bedf200-0ad5-11eb-82cc-26ccf78040cf.png)

Component to modify
[Thing](https://github.com/freedomotic/fd-vue-webapp/blob/059e0b2ef67500611e1497b993ec698bea3e6398/src/components/Thing.vue#L48)

**Comment by leobia** [comment]
Hi, as it was a fairly easy task I took the initiative to fix it. Hope you don't mind :)

**Comment by mcicolella** [comment]
It's ok. Thanks.
