### ISSUE TITLE
Customize notifications

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#232]
For "info" notifications we should have

- color: green
- position: top

Component to modify
[App.vue - ](https://github.com/freedomotic/fd-vue-webapp/blob/2acf920022d924cab6596b8643085e9771e2c69a/src/App.vue#L30)

Ref. [Quasar - Notify](https://quasar.dev/quasar-plugins/notify)

**Comment by michelvosje** [comment]
Let me try this.

**Comment by mcicolella** [comment]
Fixed in #233
