### ISSUE TITLE
Vuex introduction

### ISSUE THREAD

**Issue by P3trur0** [freedomotic/fd-vue-webapp#37]
I see that in order to deal with client I18N, it has been introduced a [dependency to **Vuex**](https://github.com/freedomotic/fd-vue-webapp/blob/870609a934df8a351b24d29dc274eebf0a886ed1/src/main.js#L6).

Is it worth to use Vuex to manage all the model of this application? Opinions anyone?

@mcicolella @williamparry

**Comment by mcicolella** [comment]
@P3trur0 the app uses many parent/child components and they communicate via props. Maybe a centralized state control with Vuex could simplify the logic but I'm not very expert. At this moment I'm reading an [article](https://medium.com/js-dojo/migrating-a-vuejs-app-to-vuex-b1762bfd4cf1) about the issue.

**Comment by P3trur0** [comment]
@mcicolella I mean, since it has already been introduced due to I18N, we could start to adopt it also to manage the remaining part of the model.

**Comment by mcicolella** [comment]
@P3trur0 Ok for me.
