### ISSUE TITLE
Thing component 

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#39]
IMHO current Polymer implementation requires some improvements 
- sensors don't show values directly but only their icon as shown in the attached image
- things' behaviors are not shown
- it's possible to create a new thing only by duplicating an existing one (after pressing '+' button that enables 'copy' feature) so you can't select a template not already present on the map

![things-list](https://user-images.githubusercontent.com/4079634/34119363-25bc6410-e422-11e7-9b7e-325bfa01d7f3.png)

**Comment by aalsiuser** [comment]
Hey, i think i can help you if you want any need for me.
I read the above comment but i didn't get the total idea of what your idea and content of the website.
I will be a waiting for your reply if you want any need for me?

**Comment by mcicolella** [comment]
Hi @aalsiuser thanks for your interest!
We already have a draft of this [component](https://github.com/freedomotic/fd-vue-webapp/blob/master/src/components/Thing.vue) as you can see in the picture.

![things](https://user-images.githubusercontent.com/4079634/38563705-cd234052-3cdd-11e8-8a14-97fed3d90257.png)


Now we are trying to place the behaviors' values for each type of thing.
E.g. lights show only a green or grey button related to their 'powered' behavior.
Instead thermostats show their temperature and the setpoint and so on.

Of course you are welcome if you want to help us.

**Comment by aalsiuser** [comment]
Thanks for your reply @mcicolella ,
I cloned you app with my local system and sincerely i have to appreciate you project and it looks really interesting.
Can you please provide me details where my help for your project will be appreciated or else you can assign me some tasks so that i can get an idea where to work on?

**Comment by mcicolella** [comment]
@aalsiuser you can take a look at the open issues and choose one or more of them if you want to contribute.

**Comment by aalsiuser** [comment]
Hey @mcicolella i started enhancing the above feature but still have many doubts can you please send me a documentation of your project or else any way of communication so that i can get you with any small doubt to complete this feature earlier.

**Comment by mcicolella** [comment]
@aalsiuser the doc is available at http://freedomotic-developer-manual.readthedocs.io/en/latest/
This Vue.js client is an improvement of an old one based on Polymer. You can try it by downloading Freedomotic from http://sourceforge.net/projects/freedomotic/files/freedomotic-commander-5.6.0-rc4.zip/download and navigate to http://localhost:8090 (admin/admin as credential). 
In you have any specific question please write here.
