### ISSUE TITLE
Introduce a static background for the client

### ISSUE THREAD

**Issue by P3trur0** [freedomotic/fd-vue-webapp#42]
At the moment, the background of each screen of the client is randomly selected from a set of Flickr URL.

We'd like to get rid of this behavior by introducing a single static asset, namely a `background.png`. Since the color of Freedomotic logo is a green one, we'd like to have an image containing either `#8bae2d` or `#75c200`.

**Comment by mcicolella** [comment]
@P3trur0 I made a search by color on Flickr 
https://labs.tineye.com/multicolr/#colors=8bae2d;weights=100;
https://labs.tineye.com/multicolr/#colors=75c200;weights=100;

We can start from them.

**Comment by P3trur0** [comment]
@mcicolella I didn't know this website: it's awesome! Are all those images royalty free?

**Comment by P3trur0** [comment]
@mcicolella alternatively we can consider something from **unsplash.com** as [these](https://unsplash.com/search/photos/green)

**Comment by mcicolella** [comment]
@P3trur0 Tineye searches Flickr so I think a lot of images are royalty free but maybe not all. We'd check it out.

**Comment by mcicolella** [comment]
Fixed in #49
