### ISSUE TITLE
Introduce responsive design

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#64]
In order to make the client responsive we need to adopt a good solution for this.
I found out 

- [vue-mq](https://github.com/AlexandreBonaventure/vue-mq)
- [vue-responsive](https://github.com/reinerBa/Vue-Responsive)

**Comment by mcicolella** [comment]
We already introduce a mobile layout based on Onsen UI. 
Maybe this issue can be closed.

**Comment by P3trur0** [comment]
I agree. For now let's close it.
