### ISSUE TITLE
Create a landing page (login form)

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#8]
The landing page should be a login form to access to the dashboard.
Something like this

![login](https://user-images.githubusercontent.com/4079634/31239372-27717732-a9fd-11e7-8d90-ebbdc67daff7.png)

The code of the old Polymer client is https://github.com/freedomotic/fd-polymer-webapp/blob/master/app/index.html

**Comment by mcastre** [comment]
hello @mcicolella! Are you currently using a third party to handle managing users? Something like [Auth0](https://auth0.com/)?

**Comment by mcicolella** [comment]
For authentication/authorization we are using Apache Shiro ( https://shiro.apache.org)

**Comment by hydeenoble** [comment]
is anyone working on this issue??

**Comment by mcicolella** [comment]
@hydenooble you can take it of you want

**Comment by mcicolella** [comment]
@hydeenoble you can take it if you want

**Comment by mcicolella** [comment]
@mcastre still interested?

**Comment by hydeenoble** [comment]
No, I have to work on something else. Apologies.

**Comment by Agrimonia** [comment]
Hi @mcicolella !Is there anything I can help with?

**Comment by mcicolella** [comment]
hi @Agrimonia you can work on this issue or on another one.

**Comment by Agrimonia** [comment]
Are you doing with this work?

**Comment by P3trur0** [comment]
@Agrimonia yes for sure, the idea is to refactor **freedomotic-polymer-app** with **Vue.js**. Any help is appreciated!

**Comment by mcicolella** [comment]
@Agrimonia are you still working on this?

**Comment by Agrimonia** [comment]
@mcicolella Well, I am tired to deal with the whole project myself. Is anyone working on this issue?

**Comment by mcicolella** [comment]
@Agrimonia I'm on it. Infact I added a first template of [Login](https://github.com/freedomotic/fd-vue-webapp/blob/master/src/components/Login.vue) component using a fake authentication system. For now.

**Comment by mcicolella** [comment]
The original code of the Polymer Login component is available [here](https://github.com/freedomotic/fd-polymer-webapp/blob/master/app/index.html#L36).
[Another nice example](https://medium.com/codeartisan/users-authentication-with-vue-js-lumen-5e58ec9e6f7e).

**Comment by williamparry** [comment]
This has been worked on here: https://github.com/freedomotic/fd-vue-webapp/pull/22

**Comment by P3trur0** [comment]
@mcicolella @williamparry I think this could be closed since a first login page draft has been implemented.
