### ISSUE TITLE
Reorganize Vuex with modules

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#85]
Now we have a single file for actions, a single file for mutations etc. We could create different modules to collect all actions related to triggers or commands or plugins etc. 
The same for mutations and application state.

**Comment by P3trur0** [comment]
@mcicolella could you please elaborate a little about this? Maybe it's worth to give priority to this issue because of the Hacktoberfest period. :jack_o_lantern:

**Comment by mcicolella** [comment]
@P3trur0 description updated
