### ISSUE TITLE
Add multilanguage support for web client

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#9]
We want to have a multilanguage web client.
For Freedomotic java client we are using i18N and the same for the old client in Polymer.
Here the code https://github.com/freedomotic/fd-polymer-i18next-translate
Please consider how to reuse the available translations https://github.com/freedomotic/fd-polymer-i18next-translate/tree/master/translation

Of course you can suggest other possible solutions.

**Comment by mcicolella** [comment]
[Here](https://stackoverflow.com/questions/46464035/how-can-i-use-lang-class-laravel-in-vue-js-2/46469501#46469501) a possible solution based on vue-18n plugin.

**Comment by mcicolella** [comment]
e4a940053419baacbb48ca4bafc03874661b42ff introduces multilanguage support based on [vuex-i18n](https://github.com/dkfbasel/vuex-i18n) plugin.

**Comment by mcicolella** [comment]
The app should set the locale automatically based on the system one. 
How to get the system locale? I found out [`os-locale`](https://github.com/sindresorhus/os-locale).
@P3trur0 what about? Any suggestion or alternative?

**Comment by mcicolella** [comment]
It seems os-locale is no more updated and there are some major issues.

**Comment by amenak77** [comment]
I found interesting this https://medium.com/@codebyjeff/using-laravel-translation-strings-in-vue-js-e2e35b7aafca. It is a general pourpose way not using i18n but php/javascript server side and vue or whatever you want as frontend

**Comment by mcicolella** [comment]
[This ](https://www.davideguida.com/how-to-detect-current-culture-in-javascript/) seems a good tip.

**Comment by amenak77** [comment]
Yes, it is an interesting POW and explains many things

**Comment by amenak77** [comment]
This boilerplate for vue applications uses i18n for traslations

https://vue-starter.herokuapp.com

**Comment by Remeic** [comment]
Hello, the problem is understand the language automatically and set language for vue-i18n right?

**Comment by mcicolella** [comment]
@Remeic exacly

**Comment by Remeic** [comment]
@mcicolella I want to try to solve the issue, if no one else has taken charge of it before

**Comment by mcicolella** [comment]
@Remeic Ok, thanks.
