### ISSUE TITLE
Add a Vuex getter to retrieve all hardware triggers

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#94]
We need a getter to retrieve from the [triggersList](https://github.com/freedomotic/fd-vue-webapp/blob/822825b3b1307d003ddfebddbb21dc03d5ee2709/src/store/index.js#L51) all the triggers having "hardwareLevel" property set to "true".

E.g. see [here](https://github.com/freedomotic/fd-vue-webapp/blob/822825b3b1307d003ddfebddbb21dc03d5ee2709/src/assets/json/triggers.json#L30)
#93

**Comment by Jeff-Duke** [comment]
PR open for this @mcicolella https://github.com/freedomotic/fd-vue-webapp/pull/198

**Comment by mcicolella** [comment]
Merged!
Thanks @Jeff-Duke
