### ISSUE TITLE
Add a Vuex getter to retrieve the list of available protocols

### ISSUE THREAD

**Issue by mcicolella** [freedomotic/fd-vue-webapp#95]
#92 This list is based on the ["protocol.name"](https://github.com/freedomotic/fd-vue-webapp/blob/822825b3b1307d003ddfebddbb21dc03d5ee2709/src/assets/json/plugins.json#L296) property in the [pluginsList](https://github.com/freedomotic/fd-vue-webapp/blob/822825b3b1307d003ddfebddbb21dc03d5ee2709/src/store/index.js#L48).

Also add an "unknown" item.
#93

**Comment by Jeff-Duke** [comment]
PR open for this: https://github.com/freedomotic/fd-vue-webapp/pull/199
